#!/usr/bin/env python
import duckdb
import sys

PLAYGROUND = "jaffle_shop.duckdb"

if __name__ == "__main__":
    args = sys.argv[1:]
    query = " ".join(args)

    if not query:
        print("Please supply a query to execute against DuckDB")
        sys.exit(1)

    conn = duckdb.connect(PLAYGROUND)
    conn.execute(query)
    print(conn.fetchall())
