name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  jaffle_shop:
    materialized: table
    staging:
      +group: staging
      +docs:
        node_color: 'silver'
      publish:
        +materialized: view
        +post_hook: [ 
            "DROP VIEW {{ this }}",
            "ALTER TABLE {{this.schema}}.{{this.identifier}}_wap RENAME TO {{ this.identifier }}",
          ]
    mart:
      +docs:
        node_color: 'gold'
