jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      threads: 24
      schema: dev
    prod:
      type: duckdb
      path: 'jaffle_shop.duckdb'
      threads: 24
      schema: prod
